# Generated by Django 5.2.6 on 2025-10-28 19:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(blank=True, default="", max_length=256)),
                (
                    "channels",
                    models.JSONField(
                        default=list, help_text="List of integer channel numbers"
                    ),
                ),
                ("duration", models.DurationField(blank=True, default=None, null=True)),
                ("state", models.IntegerField(default=0)),
                ("audiodevice_index", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="RecordingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("channel_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="RecordingTemplateChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_no", models.IntegerField()),
                ("name", models.CharField(max_length=256)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="recorder.recordingtemplate",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template", "channel_no"),
                        name="channel_no_unique_in_template",
                    )
                ],
            },
        ),
    ]
