# Generated by Django 5.2.6 on 2025-11-11 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recorder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="template",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recordings",
                to="recorder.recordingtemplate",
            ),
        ),
    ]
