# Generated by Django 4.1.2 on 2022-11-15 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recorder", "0002_alter_recording_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("channel_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="RecordingTemplateChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_no", models.IntegerField()),
                ("name", models.CharField(max_length=256)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="recorder.recordingtemplate",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="recordingtemplatechannel",
            constraint=models.UniqueConstraint(
                fields=("template", "channel_no"), name="channel_no_unique_in_template"
            ),
        ),
    ]
