# Generated by Django 4.1.2 on 2023-01-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recorder", "0003_recordingtemplate_recordingtemplatechannel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordingtemplatechannel",
            name="stereo",
            field=models.BooleanField(default=False),
        ),
    ]
