# Generated by Django 4.2.24 on 2025-09-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recorder", "0004_recordingtemplatechannel_stereo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recording",
            name="channel_count",
        ),
        migrations.AddField(
            model_name="recording",
            name="channels",
            field=models.JSONField(
                default=list, help_text="List of integer channel numbers"
            ),
        ),
    ]
