# Generated by Django 5.2.6 on 2025-10-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recorder", "0005_remove_recording_channel_count_recording_channels"),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="audiodevice_index",
            field=models.IntegerField(default=0),
        ),
    ]
