# Generated by Django 5.2.6 on 2025-10-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recorder", "0006_recording_audiodevice_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recordingtemplatechannel",
            name="stereo",
        ),
    ]
